name: Build Yocto AWS Demo - Part1

on:
  workflow_dispatch:

env:
  CACHE_DIR: /efs/gh-runners/quic-yocto
  KAS_REPO_REF_DIR: /efs/gh-runners/quic-yocto/kas-mirrors
  AWS_BUILD_HOST: codebuild-qComHweDemo-${{ github.run_id }}

jobs:
  kas-lock:
    if: github.repository == 'sampra2025/meta-qcom-hwe-ci-test'
    runs-on: awsdemo
      # codebuild-qComHweDemo-${{ github.run_id }}-${{ github.run_attempt }}
      # buildspec-override:true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run kas lock
        run: |
          whoami; id; pwd
          kas dump --update --lock --inplace ci/base.yml

      - uses: actions/upload-artifact@v4
        with:
          name: kas-lock
          path: ci/*.lock.yml

  yocto-check-layer:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/meta-qcom-hwe'
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run yocto-check-layer
        run: |
          whoami; id
          ci/yocto-check-layer.sh

  yocto-patchreview:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/meta-qcom-hwe'
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run Yocto patchreview
        run: |
          whoami; id
          ci/yocto-patchreview.sh

  