name: QCOM-HWE-AWSDemo

on:
  workflow_dispatch:

jobs:
  GH-To-AWS-CodeBuild-Integratio-Test:
    runs-on:
      - codebuild-qComHweDemo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: | 
          echo "Hello World!"
          echo "First Build from GitHub action workflow By - Satish M."
          pwd; ls -la
          uname -a; pwd; ls -la
